image: Visual Studio 2019
configuration: Release
install:
  - choco install gitversion.portable -y
before_build:
  - cmd: gitversion /l console /output buildserver
  - dotnet restore
build_script:
  msbuild /nologo /v:m /p:AssemblyVersion=%GitVersion_AssemblySemVer% /p:FileVersion=%GitVersion_MajorMinorPatch% /p:InformationalVersion=%GitVersion_InformationalVersion% /p:Configuration=%CONFIGURATION% S7.sln
after_build:
  - type S7.Net\S7.Net.csproj
  - dotnet pack S7.Net -c %CONFIGURATION% /p:Version=%GitVersion_NuGetVersion% -o artifacts
artifacts:
  - path: artifacts\*.*